api/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from api.views import get_my_event, get_help

urlpatterns = [
    url(r'^get_events/', get_my_event, name='ny_events'),
    url(r'^get_help/', get_help, name='sos'),
]

front_site/urls.py
from django.conf.urls import url, include

from front_site.views import MainPage, CompanyCreateView, CompanyUpdateView, EventCreateView, EventDetailView, \
    event_subscribe

urlpatterns = [
    url(r'^$', MainPage.as_view(), name='index'),
    url(r'^company/create/$', CompanyCreateView.as_view(), name='company_create'),
    url(r'^company/my/(?P<pk>\d+)$', CompanyUpdateView.as_view(), name='company_update'),

    url(r'^event/create/$', EventCreateView.as_view(), name='event_create'),
    url(r'^event/(?P<pk>\d+)/$', EventDetailView.as_view(), name='event_detail'),
    url(r'^event_subscribe/(?P<pk>\d+)/$', event_subscribe, name='event_subscribe'),
]

new_hackaton/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from new_hackaton import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('front_site.urls', namespace='front_site')),
    url('^', include('custom_auth.urls')),
    url(r'api/^', include('api.urls', namespace='api')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

front_site/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    phone = models.CharField(max_length=100)
    is_creator = models.BooleanField(default=False)
    enroll_id = models.CharField(max_length=500, default='')
    collection_id = models.CharField(max_length=500, default='')

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __unicode__(self):
        return self.username


class Company(models.Model):
    geo = models.CharField(max_length=300)
    name = models.CharField(max_length=500)
    user = models.ForeignKey('User')

    def __unicode__(self):
        return self.name


class Events(models.Model):
    name = models.CharField(max_length=500, default='')
    description = models.TextField(max_length=1000, default='')
    time_start = models.DateTimeField()
    time_end = models.DateTimeField()
    geo = models.CharField(max_length=300)
    company = models.ForeignKey('Company')
    users = models.ManyToManyField(User, null=True, blank=True, default=None)
    img = models.ImageField()

    def __unicode__(self):
        return self.name

front_site/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from front_site.models import User, Company, Events


class CreateCompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ['geo', 'name']

    def __init__(self, *args, **kwargs):
        super(CreateCompanyForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Company name'})
        self.fields['geo'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Geo location'})


class UpdateCompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ['geo', 'name']

    def __init__(self, *args, **kwargs):
        super(UpdateCompanyForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Company name'})
        self.fields['geo'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Geo location'})


class CreateEventForm(forms.ModelForm):
    class Meta:
        model = Events
        fields = ['name', 'description', 'time_start', 'time_end', 'geo', 'img']

    def __init__(self, *args, **kwargs):
        super(CreateEventForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Event name'})
        self.fields['geo'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Geo location'})
        self.fields['time_start'].widget.attrs.update({'class': 'begin'})
        self.fields['time_end'].widget.attrs.update({'class': 'end'})
        self.fields['description'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Event decription'})
        self.fields['img'].widget.attrs.update({'class': 'upload', 'placeholder': 'Download image'})

front_site/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView
from django.views.generic import DetailView
from django.views.generic import ListView

from front_site.forms import CreateCompanyForm, CreateEventForm, UpdateCompanyForm
from front_site.models import Company, Events


class MainPage(ListView):
    template_name = 'index.html'
    model = Events


class CompanyCreateView(CreateView):
    template_name = 'company_create.html'
    model = Company
    form_class = CreateCompanyForm
    success_url = reverse_lazy('front_site:index')


class CompanyUpdateView(UpdateView):
    template_name = 'company_update.html'
    model = Company
    form_class = UpdateCompanyForm
    success_url = reverse_lazy('front_site:index')


class EventCreateView(CreateView):
    template_name = 'event_create.html'
    model = Events
    form_class = CreateEventForm
    success_url = reverse_lazy('front_site:index')

    def form_valid(self, form):
        user = self.request.user
        form.instance.company = Company.objects.filter(user=user).first()
        return super(EventCreateView, self).form_valid(form)


class EventDetailView(DetailView):
    template_name = 'event_detail.html'
    model = Events


def event_subscribe(request, pk):
    Events.objects.filter(id=pk).first().users.add(request.user)
    return redirect('front_site:index')

front_site/templates/company_create.html
{% extends "base.html" %}

{% block content %}
    <div id="fh5co-main">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h2>Create company</h2>
                    <div class="fh5co-spacer fh5co-spacer-sm"></div>
                    <form class="form" method="post" action="{% url "front_site:company_create" %}">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ form.name }}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ form.geo }}
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <button class="btn btn-primary" type="submit">Create company</button>
                                    <input type="hidden" name="next" value="{% url "front_site:index" %}"/>
                                </div>
                            </div>
                        </div>
                    </form>

                </div>

            </div>
        </div>
    </div>
{% endblock %}

front_site/templates/company_update.html
{% extends "base.html" %}

{% block content %}
    <div id="fh5co-main">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h2>Edit company</h2>
                    <div class="fh5co-spacer fh5co-spacer-sm"></div>
                    <form class="form" method="post" action="{% url "front_site:company_update" %}">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ form.name }}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ form.geo }}
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <button class="btn btn-primary" type="submit">Login</button>
                                    <input type="hidden" name="next" value="{% url "front_site:index" %}"/>
                                </div>
                            </div>
                        </div>
                    </form>

                </div>

            </div>
        </div>
    </div>
{% endblock %}

front_site/templates/event_create.html
{% extends "base.html" %}

{% block content %}
    <div id="fh5co-main">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h2>Create company</h2>
                    <div class="fh5co-spacer fh5co-spacer-sm"></div>
                    <form class="form" method="post" action="{% url "front_site:event_create" %}">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    {{ form.name }}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ form.time_start }}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ form.time_end }}
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    {{ form.description }}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ form.geo }}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ form.img }}
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <button class="btn btn-primary" type="submit">Create event</button>
                                    <input type="hidden" name="next" value="{% url "front_site:index" %}"/>
                                </div>
                            </div>
                        </div>
                    </form>

                </div>

            </div>
        </div>
    </div>
{% endblock %}

front_site/templates/event_detail.html
{% extends "base.html" %}

{% block content %}
    <div id="fh5co-main">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h2>{{ events.name }}</h2>
                    <div class="fh5co-spacer fh5co-spacer-sm"></div>
                    <p>
                        <img src="{{ events.img.url }}" class="img-rounded img-responsive"></p>

                    <p>{{ events.time_start }} - {{ events.time_end }}</p>

                    <p>{{ events.description }}</p>

                    <a class="btn btn-primary" href="{% url "front_site:event_subscribe" pk=events.id %}">I'm in</a>

                </div>

            </div>
        </div>
    </div>
{% endblock %}

front_site/templates/index.html
{% extends "base.html" %}

{% block content %}
    <div id="fh5co-main">
        <div class="container">

            <div class="row">

                <div id="fh5co-board" data-columns>

                    {% for object in object_list %}
                        <div class="item">
                            <div class="animate-box">
                                <a href="{% url "front_site:event_detail" pk=object.id %}"
                                   class="fh5co-board-img">
                                    <img src="{{ object.img.url }}" alt="Free HTML5 Bootstrap template" >
                                </a>
                            </div>
                            <div class="fh5co-desc">
                                {{ object.name }}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}