api/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from api.views import get_my_event, get_help

urlpatterns = [
    url(r'^get_events/', get_my_event, name='ny_events'),
    url(r'^get_help/', get_help, name='sos'),
]

front_site/urls.py
from django.conf.urls import url, include

from front_site.views import MainPage, CompanyCreateView, CompanyUpdateView, EventCreateView, EventDetailView, \
    event_subscribe

urlpatterns = [
    url(r'^$', MainPage.as_view(), name='index'),
    url(r'^company/create/$', CompanyCreateView.as_view(), name='company_create'),
    url(r'^company/my/(?P<pk>\d+)$', CompanyUpdateView.as_view(), name='company_update'),

    url(r'^event/create/$', EventCreateView.as_view(), name='event_create'),
    url(r'^event/(?P<pk>\d+)/$', EventDetailView.as_view(), name='event_detail'),
    url(r'^event_subscribe/(?P<pk>\d+)/$', event_subscribe, name='event_subscribe'),
]

new_hackaton/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from new_hackaton import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('front_site.urls', namespace='front_site')),
    url('^', include('custom_auth.urls')),
    url(r'api/^', include('api.urls', namespace='api')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>i am lost</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load staticfiles %}

    <!-- Facebook and Twitter integration -->
    <meta property="og:title" content=""/>
    <meta property="og:image" content=""/>
    <meta property="og:url" content=""/>
    <meta property="og:site_name" content=""/>
    <meta property="og:description" content=""/>
    <meta name="twitter:title" content=""/>
    <meta name="twitter:image" content=""/>
    <meta name="twitter:url" content=""/>
    <meta name="twitter:card" content=""/>

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link rel="shortcut icon" href="favicon.ico">

    <!-- Google Webfonts -->
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,100,500' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

    <!-- Animate.css -->
    <link rel="stylesheet" href="{% static 'front_site/h_css/animate.css' %}">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="{% static 'front_site/h_css/icomoon.css' %}">
    <!-- Magnific Popup -->
    <link rel="stylesheet" href="{% static 'front_site/h_css/magnific-popup.css' %}">
    <!-- Salvattore -->
    <link rel="stylesheet" href="{% static 'front_site/h_css/salvattore.css' %}">
    <!-- Theme Style -->
    <link rel="stylesheet" href="{% static 'front_site/h_css/style.css' %}">
    <link rel="stylesheet" href="{% static 'front_site/css/main.css' %}">

    <link rel="stylesheet" href="{% static 'front_site/css/jquery-ui.css' %}">
    <!-- Modernizr JS -->
    <script src="{% static 'front_site/h_js/modernizr-2.6.2.min.js' %}"></script>
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->

</head>
<body>

<div id="fh5co-offcanvass">
    <a href="#" class="fh5co-offcanvass-close js-fh5co-offcanvass-close">Menu <i class="icon-cross"></i> </a>
    <h1 class="fh5co-logo"><a class="navbar-brand" href="{% url "front_site:index" %}">Iam lost</a></h1>
    <ul>
        <li class="active"><a href="{% url "front_site:index" %}">Home</a></li>
        <li><a href="{% url "login" %}">Login</a></li>
        <li><a href="{% url "registration" %}">Registration</a></li>
        {% if user.is_creator or user.is_superuser %}
{#            {% if  %}#}
{#            {% elif %}#}
            <li><a href="{% url 'front_site:company_create' %}">Create company</a></li>
            <li><a href="{% url 'front_site:event_create' %}">Create event</a></li>
        {% endif %}
    </ul>
    <h3 class="fh5co-lead">Connect with us</h3>
    <p class="fh5co-social-icons">
        <a href="#"><i class="icon-twitter"></i></a>
        <a href="#"><i class="icon-facebook"></i></a>
        <a href="#"><i class="icon-instagram"></i></a>
        <a href="#"><i class="icon-dribbble"></i></a>
        <a href="#"><i class="icon-youtube"></i></a>
    </p>
</div>
<header id="fh5co-header" role="banner">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <a href="#" class="fh5co-menu-btn js-fh5co-menu-btn">Menu <i class="icon-menu"></i></a>
                <a class="navbar-brand" href="{% url "front_site:index" %}">Iam lost</a>
            </div>
        </div>
    </div>
</header>
<!-- END .header -->

{% block content %}{% endblock %}

<footer id="fh5co-footer">

    <div class="container">
        <div class="row row-padded">
            <div class="col-md-12 text-center">
                <p class="fh5co-social-icons">
                    <a href="#"><i class="icon-twitter"></i></a>
                    <a href="#"><i class="icon-facebook"></i></a>
                    <a href="#"><i class="icon-instagram"></i></a>
                    <a href="#"><i class="icon-dribbble"></i></a>
                    <a href="#"><i class="icon-youtube"></i></a>
                </p>
            </div>
        </div>
    </div>
</footer>


<!-- jQuery -->
<script src="{% static 'front_site/h_js/jquery.min.js' %}"></script>
<!-- jQuery Easing -->
<script src="{% static 'front_site/js/jquery-ui.js' %}"></script>
<script src="{% static 'front_site/h_js/jquery.easing.1.3.js' %}"></script>
<!-- Bootstrap -->
<script src="{% static 'front_site/h_js/bootstrap.min.js' %}"></script>
<!-- Waypoints -->
<script src="{% static 'front_site/h_js/jquery.waypoints.min.js' %}"></script>
<!-- Magnific Popup -->
<script src="{% static 'front_site/h_js/jquery.magnific-popup.min.js' %}"></script>
<!-- Salvattore -->
<script src="{% static 'front_site/h_js/salvattore.min.js' %}"></script>
<!-- Main JS -->
<script src="{% static 'front_site/h_js/main.js' %}"></script>

<script>
        $(document).ready(function () {
            $(".begin").datepicker({ dateFormat: 'yy-mm-dd' });
            $(".end").datepicker({ dateFormat: 'yy-mm-dd' });
        })
    </script>

</body>
</html>